### ISSUE TITLE
Possibility of wildcard in airport definition?

### ISSUE THREAD

**Issue by marud94** [rpuig2001/Capacity-Availability-Document-CDM#3]
Is there a possibility to add the option for wildcards for airport definitions? For example if we want all Norwegian airports not specifically mentioned in the CAD to have a certain rate, we could add `ENXX,25` to automaticly set an arrival rate of 25 for all airports not listed. This would work great in the event of random group flights that would otherwise challenge capacity at smaller airports without the need to manually define all 48 airports in Norway.

**Comment by rpuig2001** [comment]
Closed here https://github.com/rpuig2001/CDM/issues/81
Thanks for the idea @marud94 👍
