### ISSUE TITLE
HTTP 404 for EPXX URL

### ISSUE THREAD

**Issue by hpeter2** [rpuig2001/Capacity-Availability-Document-CDM#7]
Plugin complains about HTTP 404 at line 106:
URL,https://markow.pl/atc/acdm_plugin/CAD_EPWW.txt

You might want to contact EPWW, if it consists

**Comment by DeathPlanet99** [comment]
Hey, there was a change of URL today. New one is on URL given below. Thanks for report. Working on it
https://cdm.plvacc.pl/acdm_plugin/CAD_EPWW.txt
